units = [
    {
        "id": "Unit1",
        "name": "Test 1",
        "status": "OK",
        "moistValue": 15000,
        "moistLimit": 18000,
        "waterTime": 1,
        "logs": [],
        "sensor": "ADS.P0",
        "valve": 27,
        "enableAutoWatering": True,
        "enableMaxWaterInterval": True,
        "enableMinWaterInterval": True,
        "maxWaterInterval": 5,
        "minWaterInterval": 1,
    },
    {
        "id": "Unit2",
        "name": "Test 2",
        "status": "OK",
        "moistValue": 15000,
        "moistLimit": 18000,
        "waterTime": 1,
        "logs": [],
        "sensor": "ADS.P1",
        "valve": 22,
        "enableAutoWatering": True,
        "enableMaxWaterInterval": True,
        "enableMinWaterInterval": True,
        "maxWaterInterval": 7,
        "minWaterInterval": 1,
    },
    {
        "id": "Unit3",
        "name": "Test 3",
        "status": "OK",
        "moistValue": 15000,
        "moistLimit": 18000,
        "waterTime": 1,
        "logs": [],
        "sensor": "ADS.P2",
        "valve": 10,
        "enableAutoWatering": True,
        "enableMaxWaterInterval": True,
        "enableMinWaterInterval": True,
        "maxWaterInterval": 7,
        "minWaterInterval": 1,
    },
    {
        "id": "Unit4",
        "name": "Test 4",
        "status": "OK",
        "moistValue": 15000,
        "moistLimit": 18000,
        "waterTime": 1,
        "logs": [],
        "sensor": "ADS.P3",
        "valve": 9,
        "enableAutoWatering": True,
        "enableMaxWaterInterval": True,
        "enableMinWaterInterval": True,
        "maxWaterInterval": 7,
        "minWaterInterval": 1,
    },
]
