units = [
    {
        "id": "Unit1",
        "name": "Anopin kieli, pullojukka ja s\u00e1bila ",
        "status": "OK",
        "moistValue": 15000,
        "moistLimit": 18000,
        "waterTime": 7,
        "logs": [],
        "sensor": "ADS.P0",
        "valve": 27,
        "enableMaxWaterInterval": True,
        "enableMinWaterInterval": True,
        "maxWaterInterval": 7,
        "minWaterInterval": 6,
    },
    {
        "id": "Unit2",
        "name": "V\u00e4h\u00e4n vett\u00e4 tarvitsevat kasvit (6)",
        "status": "OK",
        "moistValue": 15000,
        "moistLimit": 18000,
        "waterTime": 8,
        "logs": [],
        "sensor": "ADS.P1",
        "valve": 22,
        "enableMaxWaterInterval": True,
        "enableMinWaterInterval": True,
        "maxWaterInterval": 7,
        "minWaterInterval": 6,
    },
    {
        "id": "Unit3",
        "name": "Avokaadot",
        "status": "OK",
        "moistValue": 15000,
        "moistLimit": 18000,
        "waterTime": 8,
        "logs": [],
        "sensor": "ADS.P2",
        "valve": 10,
        "enableMaxWaterInterval": True,
        "enableMinWaterInterval": True,
        "maxWaterInterval": 7,
        "minWaterInterval": 6,
    },
    {
        "id": "Unit4",
        "name": "Ruusu",
        "status": "OK",
        "moistValue": 15000,
        "moistLimit": 18000,
        "waterTime": 8,
        "logs": [],
        "sensor": "ADS.P3",
        "valve": 9,
        "enableMaxWaterInterval": True,
        "enableMinWaterInterval": True,
        "maxWaterInterval": 7,
        "minWaterInterval": 6,
    },
]
